apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases/
replicas:
- name: nginx # metadata.name と一致させる
  count: 1
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx  
      labels:
        environment: develop
configMapGenerator:
- name: environments
  envs:
  - .env
